# Generated by Django 4.2.1 on 2023-11-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='big_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='ingredients',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='medium_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='thin_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
