# Generated by Django 4.2.1 on 2023-11-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_order_description_remove_order_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.TextField(default=' '),
        ),
    ]
