# Generated by Django 4.2.1 on 2023-11-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pizzeria_back', '0003_delete_product_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_pizza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(default='', max_length=100)),
                ('big_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('medium_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('thin_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ingredients', models.TextField(default='')),
                ('image', models.TextField(default=' ')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
