# Generated by Django 4.2.1 on 2023-11-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_pizza',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField(default='', max_length=100)),
                ('big_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('medium_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('thin_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ingredients', models.TextField(default='')),
                ('image', models.TextField(default=' ')),
            ],
        ),
    ]
